"""Wire schemas for the doc-processor HTTP API.

Designed to be a *superset* of the existing ai-service Gemini Vision response
shape so the ai-service can swap pipelines via a single env flag with zero
schema-handling changes:

    {"content": str, "metadata": {section_title, page_type, language}}

Doc-processor adds rich structured fields (tables, figures, formulas,
reading_order) that ai-service can ignore today and start using when
downstream features are ready.
"""
from typing import Literal

from pydantic import BaseModel, Field


# ── Request ──────────────────────────────────────────────────────────────────

class ExtractOptions(BaseModel):
    """Per-request toggles. Defaults extract everything; callers turn off what
    they don't want to pay latency for."""
    extract_tables: bool   = True
    extract_figures: bool  = True
    extract_formulas: bool = True
    ocr_fallback: bool     = True   # run OCR on regions without a text layer
    figure_captioning: bool = True  # call Florence-2 on figure crops


class ExtractRequest(BaseModel):
    """Request body for POST /v1/extract."""
    image_b64: str = Field(
        ...,
        description="Base64-encoded PNG of the rendered PDF page (RGB or RGBA).",
    )
    page_number: int = Field(
        ...,
        ge=1,
        description="1-based page number — included in the response for "
                    "downstream logging / per-page metadata.",
    )
    options: ExtractOptions = Field(default_factory=ExtractOptions)


# ── Response: structured blocks ──────────────────────────────────────────────

BlockType = Literal["text", "heading", "table", "figure", "formula", "footer"]


class BoundingBox(BaseModel):
    """Pixel-space bbox in (x_min, y_min, x_max, y_max) order, top-left origin."""
    x_min: float
    y_min: float
    x_max: float
    y_max: float


class TableData(BaseModel):
    """Structured cell data for tabular regions."""
    rows: list[list[str]]   # row-major, Markdown-friendly strings
    markdown: str           # GFM table — what gets embedded into `content`
    n_rows: int
    n_cols: int


class FigureData(BaseModel):
    """Caption + (optional) extracted text from a figure region."""
    caption: str            # generated by Florence-2; "" if disabled
    extracted_text: str     # OCR'd labels/legends from the figure; "" if none


class FormulaData(BaseModel):
    """LaTeX form of a recognised formula image."""
    latex: str              # raw LaTeX string, no $$ delimiters


class Block(BaseModel):
    """A single layout-aware block on the page."""
    type: BlockType
    content: str            # text representation suitable for chunking / embedding
    bbox: BoundingBox | None = None
    reading_order: int      # global ordinal within the page; 0 = first
    table: TableData | None = None
    figure: FigureData | None = None
    formula: FormulaData | None = None


# ── Response: page metadata ──────────────────────────────────────────────────

PageType = Literal["cover", "toc", "text", "table", "chart", "mixed", "empty"]
Language = Literal["ar", "en", "mixed"]


class PageMetadata(BaseModel):
    """Page-level metadata. Mirrors ai-service's existing Gemini Vision metadata
    keys (section_title / page_type / language) and adds structured extras."""
    section_title: str = ""
    page_type: PageType = "mixed"
    language: Language  = "mixed"

    # New structured channels — ai-service can persist these into
    # report_chunks.metadata or expose them via /reports/{id}/pages later.
    tables:  list[TableData]  = Field(default_factory=list)
    figures: list[FigureData] = Field(default_factory=list)
    formulas: list[FormulaData] = Field(default_factory=list)
    reading_order: list[int]  = Field(default_factory=list)  # block indices in order


class ExtractResponse(BaseModel):
    """Response body for POST /v1/extract.

    `content` is the canonical chunk-ready string the ai-service feeds into the
    embedding model. Tables are inlined as GFM markdown, figures as
    `[Figure: caption]`, formulas as `$$ … $$` so all extracted information
    survives chunking.

    `metadata` keeps the same three top-level fields ai-service already uses,
    plus structured channels for callers that want them.
    """
    content: str
    metadata: PageMetadata
    blocks: list[Block]                 # full block list, in reading order
    extractor: str = "doc-processor-v1" # so logs disambiguate which path ran
    page_number: int
    latency_ms: int


# ── Document-level extraction ────────────────────────────────────────────────
# Preferred path when the caller has the original PDF: avoids rasterising the
# text layer (Docling reads text directly from a digital PDF), gives reading
# order across page breaks, and amortises Docling's per-call overhead over the
# whole document.

class ExtractDocumentRequest(BaseModel):
    """Request body for POST /v1/extract_document."""
    pdf_b64: str = Field(
        ...,
        description="Base64-encoded PDF bytes.",
    )
    page_range: tuple[int, int] | None = Field(
        default=None,
        description="Optional 1-based, inclusive (lo, hi) page range. None = "
                    "all pages. Useful for retrying a specific page that "
                    "failed in a previous batch.",
    )
    options: ExtractOptions = Field(default_factory=ExtractOptions)


class DocumentMetadata(BaseModel):
    """Cross-page summary the ai-service can use for routing / filtering."""
    page_count: int
    detected_languages: list[Language]   # union of per-page languages
    has_tables:   bool
    has_figures:  bool
    has_formulas: bool


class ExtractDocumentResponse(BaseModel):
    """Response body for POST /v1/extract_document.

    `pages` preserves the same per-page shape as `ExtractResponse` so callers
    that already consume that schema (or fall back to per-page mode) can
    handle either shape uniformly.
    """
    pages: list[ExtractResponse]
    document_metadata: DocumentMetadata
    extractor: str = "doc-processor-v1"
    total_latency_ms: int


# ── Embeddings ────────────────────────────────────────────────────────────────

class EmbedRequest(BaseModel):
    """Request body for POST /v1/embed.

    `kind` selects the E5 task prefix the model was trained with:
        - "passage" for ingest-time chunks (the default — what we store in
          report_chunks.embedding)
        - "query"   for chat-time questions
    """
    texts: list[str] = Field(..., description="UTF-8 strings to embed.")
    kind: Literal["passage", "query"] = "passage"


class EmbedResponse(BaseModel):
    """One 1024-dim vector per input, in the same order. `dim` lets clients
    sanity-check against their stored schema before persisting."""
    embeddings: list[list[float]]
    dim: int = 1024
    model: str
    latency_ms: int


# ── Reranker ──────────────────────────────────────────────────────────────────

class RerankCandidate(BaseModel):
    """A candidate passage to be scored against the query.

    `id` is opaque to the reranker — the caller chooses it (typically the
    original index in their candidate list, or a chunk_id) and gets it back
    on the response so they can re-key after the rerank without sending the
    full passage payload twice."""
    id: str
    text: str


class RerankRequest(BaseModel):
    """Request body for POST /v1/rerank."""
    query: str = Field(..., description="The user question / search query.")
    candidates: list[RerankCandidate] = Field(
        ...,
        description="Passages to score. Up to a few hundred is fine; we batch internally.",
    )
    top_k: int | None = Field(
        default=None,
        description="Truncate to top N by descending score. None = return all.",
    )


class RerankResult(BaseModel):
    """One scored candidate. `score` is sigmoid-normalised to [0, 1] so
    callers can use a fixed threshold across reranker model swaps."""
    id: str
    score: float
    rank: int       # 0 = most relevant


class RerankResponse(BaseModel):
    """Response for POST /v1/rerank.

    `results` are ordered by descending score (rank=0 first). `latency_ms`
    is GPU-side only (excludes HTTP)."""
    results: list[RerankResult]
    model: str
    latency_ms: int


# ── Health ────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: Literal["healthy", "loading", "unhealthy"]
    models_loaded: dict[str, bool]      # per-model readiness
    gpu_available: bool
    version: str = "1.0.0"
