"""Wire schemas for the doc-processor HTTP API.

Designed to be a *superset* of the existing ai-service Gemini Vision response
shape so the ai-service can swap pipelines via a single env flag with zero
schema-handling changes:

    {"content": str, "metadata": {section_title, page_type, language}}

Doc-processor adds rich structured fields (tables, figures, formulas,
reading_order) that ai-service can ignore today and start using when
downstream features are ready.
"""
from typing import Literal

from pydantic import BaseModel, Field


# ── Request ──────────────────────────────────────────────────────────────────

class ExtractOptions(BaseModel):
    """Per-request toggles. Defaults extract everything; callers turn off what
    they don't want to pay latency for."""
    extract_tables: bool   = True
    extract_figures: bool  = True
    extract_formulas: bool = True
    ocr_fallback: bool     = True   # run OCR on regions without a text layer
    figure_captioning: bool = True  # call Florence-2 on figure crops


class ExtractRequest(BaseModel):
    """Request body for POST /v1/extract."""
    image_b64: str = Field(
        ...,
        description="Base64-encoded PNG of the rendered PDF page (RGB or RGBA).",
    )
    page_number: int = Field(
        ...,
        ge=1,
        description="1-based page number — included in the response for "
                    "downstream logging / per-page metadata.",
    )
    options: ExtractOptions = Field(default_factory=ExtractOptions)


# ── Response: structured blocks ──────────────────────────────────────────────

BlockType = Literal["text", "heading", "table", "figure", "formula", "footer"]


class BoundingBox(BaseModel):
    """Pixel-space bbox in (x_min, y_min, x_max, y_max) order, top-left origin."""
    x_min: float
    y_min: float
    x_max: float
    y_max: float


class TableData(BaseModel):
    """Structured cell data for tabular regions."""
    rows: list[list[str]]   # row-major, Markdown-friendly strings
    markdown: str           # GFM table — what gets embedded into `content`
    n_rows: int
    n_cols: int


class FigureData(BaseModel):
    """Caption + (optional) extracted text from a figure region."""
    caption: str            # generated by Florence-2; "" if disabled
    extracted_text: str     # OCR'd labels/legends from the figure; "" if none


class FormulaData(BaseModel):
    """LaTeX form of a recognised formula image."""
    latex: str              # raw LaTeX string, no $$ delimiters


class Block(BaseModel):
    """A single layout-aware block on the page."""
    type: BlockType
    content: str            # text representation suitable for chunking / embedding
    bbox: BoundingBox | None = None
    reading_order: int      # global ordinal within the page; 0 = first
    table: TableData | None = None
    figure: FigureData | None = None
    formula: FormulaData | None = None


# ── Response: page metadata ──────────────────────────────────────────────────

PageType = Literal["cover", "toc", "text", "table", "chart", "mixed", "empty"]
Language = Literal["ar", "en", "mixed"]


class PageMetadata(BaseModel):
    """Page-level metadata. Mirrors ai-service's existing Gemini Vision metadata
    keys (section_title / page_type / language) and adds structured extras."""
    section_title: str = ""
    page_type: PageType = "mixed"
    language: Language  = "mixed"

    # New structured channels — ai-service can persist these into
    # report_chunks.metadata or expose them via /reports/{id}/pages later.
    tables:  list[TableData]  = Field(default_factory=list)
    figures: list[FigureData] = Field(default_factory=list)
    formulas: list[FormulaData] = Field(default_factory=list)
    reading_order: list[int]  = Field(default_factory=list)  # block indices in order


class ExtractResponse(BaseModel):
    """Response body for POST /v1/extract.

    `content` is the canonical chunk-ready string the ai-service feeds into the
    embedding model. Tables are inlined as GFM markdown, figures as
    `[Figure: caption]`, formulas as `$$ … $$` so all extracted information
    survives chunking.

    `metadata` keeps the same three top-level fields ai-service already uses,
    plus structured channels for callers that want them.
    """
    content: str
    metadata: PageMetadata
    blocks: list[Block]                 # full block list, in reading order
    extractor: str = "doc-processor-v1" # so logs disambiguate which path ran
    page_number: int
    latency_ms: int


# ── Document-level extraction ────────────────────────────────────────────────
# Preferred path when the caller has the original PDF: avoids rasterising the
# text layer (Docling reads text directly from a digital PDF), gives reading
# order across page breaks, and amortises Docling's per-call overhead over the
# whole document.

class ExtractDocumentRequest(BaseModel):
    """Request body for POST /v1/extract_document."""
    pdf_b64: str = Field(
        ...,
        description="Base64-encoded PDF bytes.",
    )
    page_range: tuple[int, int] | None = Field(
        default=None,
        description="Optional 1-based, inclusive (lo, hi) page range. None = "
                    "all pages. Useful for retrying a specific page that "
                    "failed in a previous batch.",
    )
    options: ExtractOptions = Field(default_factory=ExtractOptions)


class DocumentMetadata(BaseModel):
    """Cross-page summary the ai-service can use for routing / filtering."""
    page_count: int
    detected_languages: list[Language]   # union of per-page languages
    has_tables:   bool
    has_figures:  bool
    has_formulas: bool


class ExtractDocumentResponse(BaseModel):
    """Response body for POST /v1/extract_document.

    `pages` preserves the same per-page shape as `ExtractResponse` so callers
    that already consume that schema (or fall back to per-page mode) can
    handle either shape uniformly.
    """
    pages: list[ExtractResponse]
    document_metadata: DocumentMetadata
    extractor: str = "doc-processor-v1"
    total_latency_ms: int


# ── Embeddings ────────────────────────────────────────────────────────────────

class EmbedRequest(BaseModel):
    """Request body for POST /v1/embed.

    `kind` selects the E5 task prefix the model was trained with:
        - "passage" for ingest-time chunks (the default — what we store in
          report_chunks.embedding)
        - "query"   for chat-time questions
    """
    texts: list[str] = Field(..., description="UTF-8 strings to embed.")
    kind: Literal["passage", "query"] = "passage"


class EmbedResponse(BaseModel):
    """One vector per input, in the same order. `dim` lets clients
    sanity-check against their stored schema before persisting.

    Note (2026-04-30): /v1/embed is in legacy mode — production now uses
    Vertex gemini-embedding-001 directly from ai-service. This endpoint
    remains for ad-hoc tooling but its embeddings live in a different
    vector space than the production index, so don't mix them."""
    embeddings: list[list[float]]
    dim: int = 768
    model: str
    latency_ms: int


# ── Reranker ──────────────────────────────────────────────────────────────────

class RerankCandidate(BaseModel):
    """A candidate passage to be scored against the query.

    `id` is opaque to the reranker — the caller chooses it (typically the
    original index in their candidate list, or a chunk_id) and gets it back
    on the response so they can re-key after the rerank without sending the
    full passage payload twice."""
    id: str
    text: str


class RerankRequest(BaseModel):
    """Request body for POST /v1/rerank."""
    query: str = Field(..., description="The user question / search query.")
    candidates: list[RerankCandidate] = Field(
        ...,
        description="Passages to score. Up to a few hundred is fine; we batch internally.",
    )
    top_k: int | None = Field(
        default=None,
        description="Truncate to top N by descending score. None = return all.",
    )


class RerankResult(BaseModel):
    """One scored candidate. `score` is sigmoid-normalised to [0, 1] so
    callers can use a fixed threshold across reranker model swaps."""
    id: str
    score: float
    rank: int       # 0 = most relevant


class RerankResponse(BaseModel):
    """Response for POST /v1/rerank.

    `results` are ordered by descending score (rank=0 first). `latency_ms`
    is GPU-side only (excludes HTTP)."""
    results: list[RerankResult]
    model: str
    latency_ms: int


# ── /v1/ingest_full ──────────────────────────────────────────────────────────
# End-to-end ingest in one round-trip. Replaces the legacy flow where
# ai-service called /v1/extract_document, received ~100 MB of structured
# blocks, then chunked + embedded locally. With ingest_full the doc-processor
# does extract → chunk → embed and returns just chunks + vectors (~2-3 MB
# for a 134-page PDF). The ai-service worker only persists.


class IngestFullOptions(BaseModel):
    """Per-request toggles for the combined extract + chunk + embed path.

    Inherits all extractor flags so callers can mirror what they pass to
    /v1/extract_document. `embed_chunks=False` skips the Vertex round-trip
    and returns chunks without vectors — useful for dry-runs and chunk-
    boundary debugging.
    """
    extract_tables: bool   = True
    extract_figures: bool  = True
    extract_formulas: bool = True
    ocr_fallback: bool     = True
    figure_captioning: bool = True
    embed_chunks: bool     = True


class IngestFullRequest(BaseModel):
    """Request body for POST /v1/ingest_full."""
    pdf_b64: str = Field(
        ...,
        description="Base64-encoded PDF bytes.",
    )
    options: IngestFullOptions = Field(default_factory=IngestFullOptions)


class IngestChunk(BaseModel):
    """One ingest-ready chunk: text + section + embedding."""
    page_number: int
    chunk_index: int
    content: str
    section_title: str = ""
    block_types: list[str] = Field(default_factory=list)
    # 768-dim vector when options.embed_chunks=True; empty list otherwise.
    embedding: list[float] = Field(default_factory=list)


class IngestFullStats(BaseModel):
    """Per-stage timing so the caller can see where time was spent."""
    extract_latency_ms: int
    chunk_latency_ms:   int
    embed_latency_ms:   int
    total_latency_ms:   int
    pages_processed:    int
    chunks_emitted:     int


class IngestFullResponse(BaseModel):
    """Response body for POST /v1/ingest_full.

    Wire size for a 134-page PDF with ~277 chunks: ~2-3 MB (vs ~100 MB for
    the equivalent /v1/extract_document response). The size delta is the
    point of this endpoint.
    """
    document_metadata: DocumentMetadata
    chunks: list[IngestChunk]
    extractor: str = "doc-processor-v1"
    embed_model: str = ""           # "" when options.embed_chunks=False
    embed_dim: int = 0              # 0 when options.embed_chunks=False
    stats: IngestFullStats


# ── /v1/ingest — full GPU-side ingest (download → extract → chunk → embed → persist)
# Two sub-modes share the same pipeline (run_ingest):
#
#   /v1/ingest       — synchronous. Returns full stats when done. Used by the
#                      ai-service worker for ingest+summarize jobs (worker
#                      manages the ai_jobs row lifecycle itself).
#
#   /v1/ingest_job   — asynchronous. Accepts {job_id, ...}, returns 202
#                      immediately, then runs the pipeline in a background
#                      task and updates ai_jobs directly. The ai-service
#                      worker never touches these jobs.

class IngestOptions(BaseModel):
    """Extraction toggles for /v1/ingest. Same flags as ExtractOptions."""
    extract_tables: bool    = True
    extract_figures: bool   = True
    extract_formulas: bool  = True
    ocr_fallback: bool      = True
    figure_captioning: bool = True


class IngestRequest(BaseModel):
    """Request body for POST /v1/ingest."""
    report_id: str = Field(
        ...,
        description="UUID of the report row — used as the ReportId FK in report_chunks.",
    )
    file_url: str = Field(
        ...,
        description="gs://bucket/path.pdf or https:// URL of the source PDF.",
    )
    options: IngestOptions = Field(default_factory=IngestOptions)


class IngestResponse(BaseModel):
    """Stats returned by POST /v1/ingest (synchronous path).

    Shape matches the OutputData written into ai_jobs by ai-service's
    run_ingest_only_job so callers can read either path's result uniformly.
    """
    report_id: str
    pages_processed: int
    chunks_inserted: int
    pages_total: int
    extractor: str
    embed_model: str
    embed_dim: int
    total_latency_ms: int


class IngestJobRequest(BaseModel):
    """Request body for POST /v1/ingest_job (async, GPU-managed job lifecycle)."""
    job_id: str = Field(
        ...,
        description="UUID of the ai_jobs row. The GPU will atomically claim it "
                    "(Pending → Processing) and drive it to Completed or Failed.",
    )
    report_id: str
    file_url: str = Field(
        ...,
        description="gs://bucket/path.pdf or https:// URL of the source PDF.",
    )
    options: IngestOptions = Field(default_factory=IngestOptions)


class IngestJobAccepted(BaseModel):
    """Response for POST /v1/ingest_job — returned immediately before processing starts."""
    accepted: bool = True
    job_id: str


# ── Health ────────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: Literal["healthy", "loading", "unhealthy"]
    models_loaded: dict[str, bool]      # per-model readiness
    gpu_available: bool
    version: str = "1.0.0"
